/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg23vvv1;

import java.io.BufferedInputStream;
import java.io.BufferedReader;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;


import java.io.FileNotFoundException;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.SwingUtilities;
import java.util.concurrent.Callable;
import java.util.concurrent.Future;
import java.util.ArrayList;
import java.util.List;


import java.util.LinkedList;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

 

/**
 *
 * @author student
 */
public class JForm extends javax.swing.JFrame {
    
    private static LinkedList<RecIntegral> tableContent = new LinkedList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JForm.class.getName());
    
    private ExecutorService executor = Executors.newFixedThreadPool(10);    /**
     * Creates new form JForm
     */
    public JForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDeleted = new javax.swing.JButton();
        jButtonSolve = new javax.swing.JButton();
        jTextFieldLowerBound = new javax.swing.JTextField();
        jTextFieldStepBound = new javax.swing.JTextField();
        jTextFieldUpperBound = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonClearTable = new javax.swing.JButton();
        jButtonAddCollection = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1SaveTxt = new javax.swing.JMenuItem();
        jMenuItem2LoadTxt = new javax.swing.JMenuItem();
        jMenuItem3SaveBin = new javax.swing.JMenuItem();
        jMenuItem4LoadBin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(176, 208, 211));

        jLabel1.setText("Формула: ");

        jLabel2.setText("Нижний порог");

        jLabel3.setText("Верхний порог");

        jLabel4.setText("Шаг");

        jButtonAdd.setBackground(new java.awt.Color(247, 227, 175));
        jButtonAdd.setText("Добавить");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDeleted.setBackground(new java.awt.Color(247, 227, 175));
        jButtonDeleted.setText("Удалить");
        jButtonDeleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletedActionPerformed(evt);
            }
        });

        jButtonSolve.setBackground(new java.awt.Color(247, 227, 175));
        jButtonSolve.setText("Вычислить");
        jButtonSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolveActionPerformed(evt);
            }
        });

        jTextFieldLowerBound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLowerBoundActionPerformed(evt);
            }
        });

        jTextFieldStepBound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStepBoundActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(247, 175, 157));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Нижний порог", "Верхний порог", "Шаг", "Результат"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(204, 238, 188));
        jTable1.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane4.setViewportView(jTable1);

        jButtonClearTable.setBackground(new java.awt.Color(247, 227, 175));
        jButtonClearTable.setText("Очистить таблицу");
        jButtonClearTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearTableActionPerformed(evt);
            }
        });

        jButtonAddCollection.setBackground(new java.awt.Color(247, 227, 175));
        jButtonAddCollection.setText("Добавление из коллекциии");
        jButtonAddCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCollectionActionPerformed(evt);
            }
        });

        jLabel5.setText("(e^x)/x");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldLowerBound, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(jTextFieldUpperBound)
                                    .addComponent(jTextFieldStepBound)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAddCollection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonClearTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDeleted, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSolve))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAdd)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAddCollection, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(3, 3, 3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonClearTable)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonDeleted)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSolve))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldLowerBound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldUpperBound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldStepBound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Меню");

        jMenuItem1SaveTxt.setText("Сохранить как txt");
        jMenuItem1SaveTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1SaveTxtActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1SaveTxt);

        jMenuItem2LoadTxt.setText("Загрузить как txt");
        jMenuItem2LoadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2LoadTxtActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2LoadTxt);

        jMenuItem3SaveBin.setText("Сохранить как bin");
        jMenuItem3SaveBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3SaveBinActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3SaveBin);

        jMenuItem4LoadBin.setText("Загрузить как bin");
        jMenuItem4LoadBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4LoadBinActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4LoadBin);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shutdownExecutor() {
    executor.shutdown();
}
    
    private void jButtonSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolveActionPerformed
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow != -1) {
        try {
            // Получаем параметры из таблицы
            double a = Double.parseDouble(jTable1.getValueAt(selectedRow, 0).toString());
            double b = Double.parseDouble(jTable1.getValueAt(selectedRow, 1).toString());
            double step = Double.parseDouble(jTable1.getValueAt(selectedRow, 2).toString());

            RecIntegral ri = new RecIntegral(a, b, step);
            
            // Создаем и запускаем задачу в пуле потоков
            CalculationTask task = new CalculationTask(ri, (DefaultTableModel)jTable1.getModel(), selectedRow);
            executor.submit(task);
            
            tableContent.add(ri);
            javax.swing.SwingUtilities.invokeLater(() -> {
                jTable1.setValueAt("Вычисляется...", selectedRow, 3);
            });
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Введите корректные числа (разделитель дробной части - точка). ",
                "Ошибка ввода", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ошибка", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButtonSolveActionPerformed

    private void jButtonDeletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletedActionPerformed
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() != -1){
            tModel.removeRow(jTable1.getSelectedRow());
            tableContent.remove(jTable1.getSelectedRow());
        }
        
    }//GEN-LAST:event_jButtonDeletedActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        double up, low, step; 
        try{
            low = Double.parseDouble(jTextFieldLowerBound.getText());
            up = Double.parseDouble(jTextFieldUpperBound.getText());
            step = Double.parseDouble(jTextFieldStepBound.getText());

            RecIntegral ri = new RecIntegral(low, up, step);
            tableContent.add(ri);

            DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();

            tModel.addRow(new Object[] {ri.GetLowLim(), ri.GetUpperLim(), ri.GetStep()});
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,
            "Введите корректные числа (разделитель дробной части - точка). ",
            "Ошибка ввода", JOptionPane.ERROR_MESSAGE);
        }
        catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this,
            e.getMessage(),
            "Ошибка", JOptionPane.ERROR_MESSAGE);
        }
        catch (InvalidRangeException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ошибка диапазона", JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldLowerBoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLowerBoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLowerBoundActionPerformed

    private void jTextFieldStepBoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStepBoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStepBoundActionPerformed

    private void jButtonClearTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearTableActionPerformed
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        tModel.setNumRows(0);

    }//GEN-LAST:event_jButtonClearTableActionPerformed

    private void jButtonAddCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCollectionActionPerformed
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        tModel.setNumRows(0);
        
        for(RecIntegral item: tableContent){
            tModel.addRow(new Object[]{
                item.GetLowLim(),
                item.GetUpperLim(),
                item.GetStep(),
                item.GetResult()
            });
        };
    }//GEN-LAST:event_jButtonAddCollectionActionPerformed

    private void jMenuItem1SaveTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1SaveTxtActionPerformed
        JFileChooser f = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text file (*.txt)", "txt");
        f.setFileFilter(filter);
        f.showSaveDialog(null);
        
        File file = f.getSelectedFile();
        
        if (!file.getPath().endsWith(".txt")){
            file = new File(file.getPath() + ".txt");
        }
        
        try(FileWriter writer = new FileWriter(file, false)){
            for (RecIntegral o : tableContent){
                writer.write(o.GetLowLim() + " " +
                        o.GetUpperLim() + " " +
                        o.GetStep() + " " + 
                        o.GetResult() + "\n");
            }
            writer.flush();
            writer.close();
        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jMenuItem1SaveTxtActionPerformed

    private void jMenuItem2LoadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2LoadTxtActionPerformed
        JFileChooser f = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Text file (*.txt)", "txt");
    f.setFileFilter(filter);
    
    int result = f.showOpenDialog(null);
    
    if (result != JFileChooser.APPROVE_OPTION) {
        return;
    }
    
    File file = f.getSelectedFile();
    
    if (file == null || !file.exists()) {
        JOptionPane.showMessageDialog(null, "File not found");
        return;
    }
    
    try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
        tableContent.clear();
        String temp = "";
        
        while ((temp = reader.readLine()) != null) {
            temp = temp.trim();
            if (temp.isEmpty()) continue;
            
            String[] parts = temp.split(" ");
            
            if (parts.length != 4) {
                JOptionPane.showMessageDialog(null, "Invalid format: expected 4 values, found " + parts.length);
                continue;
            }
            
            try {
                RecIntegral rec = new RecIntegral(
                    Double.parseDouble(parts[0]),
                    Double.parseDouble(parts[1]),
                    Double.parseDouble(parts[2]),
                    Double.parseDouble(parts[3])
                );
                tableContent.add(rec);
            } catch (InvalidRangeException e) {
                JOptionPane.showMessageDialog(null, "Invalid data: " + e.getMessage());
                // Skip this record or handle as needed
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid number format: " + temp);
            }
        }
        
        // Refresh the table display
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for (RecIntegral obj : tableContent) {
            model.addRow(new Object[]{
                obj.GetLowLim(),     // Note: capital 'G'
                obj.GetUpperLim(),   // Note: capital 'G'
                obj.GetStep(),       // Note: capital 'G'
                obj.GetResult()      // Note: capital 'G'
            });
        }
        
        JOptionPane.showMessageDialog(null, "Successfully loaded " + tableContent.size() + " records");
        
    } catch (FileNotFoundException ex) {
        JOptionPane.showMessageDialog(null, "File not found: " + ex.getMessage());
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "Error reading file: " + ex.getMessage());
    }


    }//GEN-LAST:event_jMenuItem2LoadTxtActionPerformed

    private void jMenuItem3SaveBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3SaveBinActionPerformed
    JFileChooser f = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Binary file (*.bin)", "bin");
    f.setFileFilter(filter);
    f.showSaveDialog(null);
    
    File file = f.getSelectedFile();
    
    if(!file.getPath().endsWith(".bin")){
        file = new File(file.getPath() + ".bin");
    }
    
    try(ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream(file))){
        out.writeObject(tableContent);
        out.flush();
        out.close();
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "Error reading file: " + ex.getMessage());
    }
    
    }//GEN-LAST:event_jMenuItem3SaveBinActionPerformed

    private void jMenuItem4LoadBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4LoadBinActionPerformed
        JFileChooser f = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Binary file (*.bin)", "bin");
    f.setFileFilter(filter);
    
    int result = f.showOpenDialog(null);
    if (result != JFileChooser.APPROVE_OPTION) {
        return; // User cancelled
    }
    
    File file = f.getSelectedFile();
    
    try (ObjectInputStream in = new ObjectInputStream(new BufferedInputStream(new FileInputStream(file)))) {
        tableContent = (LinkedList<RecIntegral>) in.readObject();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for (RecIntegral obj : tableContent) {
            model.addRow(new Object[]{
                obj.GetLowLim(),
                obj.GetUpperLim(),
                obj.GetStep(),
                obj.GetResult()
            });
        }
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "Error reading file: " + ex.getMessage());
    } catch (ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(null, "Error: Class not found - " + ex.getMessage());
    }
    
    }//GEN-LAST:event_jMenuItem4LoadBinActionPerformed

   
class PartialIntegralTask implements Callable<Double> {
    private double a;      // нижняя граница части
    private double b;      // верхняя граница части
    private double step;   // шаг
    
    public PartialIntegralTask(double a, double b, double step) {
        this.a = a;
        this.b = b;
        this.step = step;
    }
    
    @Override
    public Double call() throws Exception {
        String threadName = Thread.currentThread().getName();
        double sum = 0;
        
        for (double x = a; x < b; x += step) {
            double h = step;
            if (x + step > b) {
                h = b - x;
            }
            double fx = Math.exp(x) / x;
            sum += fx * h;
        }
        
        System.out.println("Поток " + threadName + " вычислил часть интеграла от " + a + " до " + b + " = " + sum);
        return sum;
    }
}
    
private double calculateParallel(double low, double up, double step) throws Exception {
    double intervalLength = up - low;
    double partLength = intervalLength / 10;
    
    List<Callable<Double>> tasks = new ArrayList<>();
    
    for (int i = 0; i < 10; i++) {
        double partA = low + i * partLength;
        double partB = (i == 9) ? up : low + (i + 1) * partLength;
        
        PartialIntegralTask task = new PartialIntegralTask(partA, partB, step);
        tasks.add(task);
    }
    
    List<Future<Double>> futures = executor.invokeAll(tasks);
    
    double totalSum = 0;
    for (Future<Double> future : futures) {
        totalSum += future.get();
    }
    
    return totalSum;
}


class CalculationTask implements Runnable {
    private RecIntegral recIntegral;
    private DefaultTableModel tableModel;
    private int selectedRow;

    public CalculationTask(RecIntegral recIntegral, DefaultTableModel tableModel, int selectedRow) {
        this.recIntegral = recIntegral;
        this.tableModel = tableModel;
        this.selectedRow = selectedRow;
    }
    
    @Override
    public void run() {
        String threadName = Thread.currentThread().getName();
        System.out.println("Главный поток " + threadName + " начинает вычисление интеграла для строки " + selectedRow);
        
        try {
            double result = calculateParallel(
                recIntegral.GetLowLim(), 
                recIntegral.GetUpperLim(), 
                recIntegral.GetStep()
            );
            
            recIntegral.setResult(result);
            
            SwingUtilities.invokeLater(() -> {
                tableModel.setValueAt(String.format("%.10e", recIntegral.GetResult()), selectedRow, 3);            });
        } catch (Exception e) {
            System.err.println("Ошибка: " + e.getMessage());
            SwingUtilities.invokeLater(() -> {
                tableModel.setValueAt("Ошибка: " + e.getMessage(), selectedRow, 3);
                JOptionPane.showMessageDialog(null, "Ошибка вычисления: " + e.getMessage());
            });
        }
    }
}

@Override
public void dispose() {
    executor.shutdown();
    super.dispose();
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddCollection;
    private javax.swing.JButton jButtonClearTable;
    private javax.swing.JButton jButtonDeleted;
    private javax.swing.JButton jButtonSolve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1SaveTxt;
    private javax.swing.JMenuItem jMenuItem2LoadTxt;
    private javax.swing.JMenuItem jMenuItem3SaveBin;
    private javax.swing.JMenuItem jMenuItem4LoadBin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldLowerBound;
    private javax.swing.JTextField jTextFieldStepBound;
    private javax.swing.JTextField jTextFieldUpperBound;
    // End of variables declaration//GEN-END:variables
}
