/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg23vvv1;

import java.util.LinkedList;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author student
 */
public class JForm extends javax.swing.JFrame {
    
    private static LinkedList<RecIntegral> tableContent = new LinkedList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JForm.class.getName());

    /**
     * Creates new form JForm
     */
    public JForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDeleted = new javax.swing.JButton();
        jButtonSolve = new javax.swing.JButton();
        jTextFieldLowerBound = new javax.swing.JTextField();
        jTextFieldStepBound = new javax.swing.JTextField();
        jTextFieldUpperBound = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonClearTable = new javax.swing.JButton();
        jButtonAddCollection = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(176, 208, 211));

        jLabel1.setText("Формула: ");

        jLabel2.setText("Нижний порог");

        jLabel3.setText("Верхний порог");

        jLabel4.setText("Шаг");

        jButtonAdd.setBackground(new java.awt.Color(247, 227, 175));
        jButtonAdd.setText("Добавить");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDeleted.setBackground(new java.awt.Color(247, 227, 175));
        jButtonDeleted.setText("Удалить");
        jButtonDeleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletedActionPerformed(evt);
            }
        });

        jButtonSolve.setBackground(new java.awt.Color(247, 227, 175));
        jButtonSolve.setText("Вычислить");
        jButtonSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolveActionPerformed(evt);
            }
        });

        jTextFieldLowerBound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLowerBoundActionPerformed(evt);
            }
        });

        jTextFieldStepBound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStepBoundActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(247, 175, 157));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Нижний порог", "Верхний порог", "Шаг", "Результат"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(204, 238, 188));
        jTable1.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane4.setViewportView(jTable1);

        jButtonClearTable.setBackground(new java.awt.Color(247, 227, 175));
        jButtonClearTable.setText("Очистить таблицу");
        jButtonClearTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearTableActionPerformed(evt);
            }
        });

        jButtonAddCollection.setBackground(new java.awt.Color(247, 227, 175));
        jButtonAddCollection.setText("Добавление из коллекциии");
        jButtonAddCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCollectionActionPerformed(evt);
            }
        });

        jLabel5.setText("(e^x)/x");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldLowerBound, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(jTextFieldUpperBound)
                                    .addComponent(jTextFieldStepBound)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAddCollection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonClearTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDeleted, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSolve))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAdd)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAddCollection, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(3, 3, 3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonClearTable)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonDeleted)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSolve))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldLowerBound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldUpperBound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldStepBound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolveActionPerformed
    int selectedRow = jTable1.getSelectedRow();
    int row = jTable1.getSelectedRow();
    double result = 0.0;
    if (selectedRow != -1) {
        try{
            double a = Double.parseDouble(jTable1.getValueAt(selectedRow, 0).toString());
            double b = Double.parseDouble(jTable1.getValueAt(selectedRow, 1).toString());
            double step = Double.parseDouble(jTable1.getValueAt(selectedRow, 2).toString());

            RecIntegral ri = new RecIntegral(a, b, step);
            result = ri.calculate(ri.GetLowLim(), ri.GetUpperLim(), ri.GetStep());

            ri.setResult(result);
            tableContent.add(ri);

            jTable1.setValueAt(ri.GetResult(), selectedRow, 3);
            tableContent.set(selectedRow, ri);
        }
        catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this,
            "Введите корректные числа (разделитель дробной части - точка). ",
            "Ошибка ввода", JOptionPane.ERROR_MESSAGE);
        }
        catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this,
            e.getMessage(),
            "Ошибка", JOptionPane.ERROR_MESSAGE);
        }
        catch (InvalidRangeException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ошибка диапазона", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButtonSolveActionPerformed

    private void jButtonDeletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletedActionPerformed
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() != -1){
            tModel.removeRow(jTable1.getSelectedRow());
            tableContent.remove(jTable1.getSelectedRow());
        }
        
    }//GEN-LAST:event_jButtonDeletedActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        double up, low, step; 
        try{
            low = Double.parseDouble(jTextFieldLowerBound.getText());
            up = Double.parseDouble(jTextFieldUpperBound.getText());
            step = Double.parseDouble(jTextFieldStepBound.getText());

            RecIntegral ri = new RecIntegral(low, up, step);
            tableContent.add(ri);

            DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();

            tModel.addRow(new Object[] {ri.GetLowLim(), ri.GetUpperLim(), ri.GetStep()});
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,
            "Введите корректные числа (разделитель дробной части - точка). ",
            "Ошибка ввода", JOptionPane.ERROR_MESSAGE);
        }
        catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this,
            e.getMessage(),
            "Ошибка", JOptionPane.ERROR_MESSAGE);
        }
        catch (InvalidRangeException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Ошибка диапазона", JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldLowerBoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLowerBoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLowerBoundActionPerformed

    private void jTextFieldStepBoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStepBoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStepBoundActionPerformed

    private void jButtonClearTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearTableActionPerformed
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        tModel.setNumRows(0);

    }//GEN-LAST:event_jButtonClearTableActionPerformed

    private void jButtonAddCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCollectionActionPerformed
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        tModel.setNumRows(0);
        
        for(RecIntegral item: tableContent){
            tModel.addRow(new Object[]{
                item.GetLowLim(),
                item.GetUpperLim(),
                item.GetStep(),
                item.GetResult()
            });
        };
    }//GEN-LAST:event_jButtonAddCollectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddCollection;
    private javax.swing.JButton jButtonClearTable;
    private javax.swing.JButton jButtonDeleted;
    private javax.swing.JButton jButtonSolve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldLowerBound;
    private javax.swing.JTextField jTextFieldStepBound;
    private javax.swing.JTextField jTextFieldUpperBound;
    // End of variables declaration//GEN-END:variables
}
